<?php

use Illuminate\Database\Seeder;

class CompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // INSERT INTO `company` (`id`, `user_id`, `name`, `size`, `address`, `place`, `image`, `desc`, `website`, `phone`, `view`, `status`) VALUES
        // (1, 3, 'Công ty test', '5', '12 Nguyễn Văn Bảo, phường 5, quận Gò Vấp', '3', 'public/images/company/jLO8y6pdcQthiet-ke-logo-cong-ty-thuong-mai-phuong-bac-pbc_thumb_1466496409.jpg', '-Đây là nội dung test', 'https://laravel.com', '0988936352', 2, '1'),
        // (2, 2, 'Công ty test 2', '4', '12 Nguyễn Văn Bảo, phường 5, quận Gò Vấp', '2', 'public/images/company/0LDdoZ5SPDthiet-ke-logo-cong-ty-dung-dong.jpg', 'sadasdasdasdasdasdasdasdasdasd', 'https://laravel.com', '988936354', 1, '1'),
        // (3, 4, 'RIKKEISOFT', '5', 'Nam Tu Liem, Ha Noi', '2', 'public/images/company/h1wqBo5CNcrikkeisoft-logo-170-151.png', 'RIKKEISOFT là một trong những công ty hàng đầu tại Việt Nam về sản xuất phần mềm, đặc biệt là ứng dụng trên nền web và smartphone. Làm việc cho 100% khách hàng Nhật Bản.\r\n\r\nTháng 10 năm 2014 Rikkeisoft đã trở thành một trong 30 doanh nghiệp CNTT hàng đầu của Việt Nam, vừa được VINASA công bố, giới thiệu và quảng bá tới các khách hàng, đối tác tiềm năng tại gần 100 quốc gia, vùng lãnh thổ trên thế giới!\r\n\r\nRIKKEISOFT được thành lập ngày 06 tháng 04 năm 2012. Kể từ khi thành lập, chúng tôi luôn nỗ lực để tạo ra những sản phẩm mang tính sáng tạo có chất lượng tốt, cống hiến cho sự phát triển của xã hội. Sứ mệnh của chúng tôi là xây dựng nên cuộc sống tốt đẹp hơn nhờ có di động và Internet. Tầm nhìn của chúng tôi là trở thành một trong những công ty lớn nhất tại Việt Nam trong lĩnh vực smartphone, web và di động trong 5 năm tới.', 'https://RIKKEISOFT.com', '0988936354', 2, '1'),
        // (4, 9, 'NEC Vietnam', '5', '364 Cong Hoa Tan Binh Ho Chi Minh', '3', 'public/images/company/HaVhBIbVEInec-vietnam-logo-170-151.png', 'NEC established its liaison office in Vietnam in the early 1990’s. In line with its growth strategy, it was re-organized as NEC Vietnam Co., Ltd. in 2006, with a newfound commitment to grow the business and contribute towards the people and society of Vietnam.\r\n\r\nIn a rapidly changing business environment, we have evolved to be a comprehensive solution provider, to deliver on our core strengths of providing Solutions for Society, which involves providing social infrastructure benefiting citizens and communities.\r\n\r\nToday, we are highly dependent on ICT technologies. We are proud to say that NEC is well-positioned to meet the needs of the market, to have the relevant technologies in-house and is ready to deliver.\r\nRefer to http://vn.nec.com/en_VN/about/necvn/recruitment/ for new chances and do not hesitate to apply to NEC VietNam.', 'http://vn.nec.com/', '0988936354', 1, '1'),
        // (5, 10, 'FPT Software', '2', 'F-Town Building, Lot T2, D1 Street District 9 Ho Chi Minh', '3', 'public/images/company/y6cddTBx7xfpt-software-logo-170-151.png', 'Join FPT Software – You can make it too! \r\n\r\nYou can catch up with unlimited opportunities to work and live in different countries over the world, join world class software projects with trendiest technologies, innovative products & services that bring great values to millions of people around the world, such as the world’s largest airplane brand, biggest broadcast satellite services in the US, the leading manufacturer of postage meter and mailroom equipment in EU, etc. \r\n\r\nYou can choose your career path to become a technology expert or a professional manager which best fits your desire, qualifications and characteristics in an equal opportunity and open-minded culture workplace. \r\n\r\nYou can balance your working and spiritual life in the environment of youth, multinational culture and creativity, improve impressively vital soft skills including English, Japanese, French… and communication skills through daily direct communication with global customers and employees. \r\n\r\nFPT Software is proud to accompany with thousands of individuals to continuously develop and explore their career path. \r\n\r\nYou can make it too!', 'https://fptshop.com.vn/', '0988936354', 1, '1'),
        // (6, 11, 'OHMYLAB VIET NAM', '2', 'H3 Buidling, 384 Hoang Dieu, Ward 6 District 4 Ho Chi Minh', '2', 'public/images/company/KBpN7mKvZUohmylab-viet-nam-logo-170-151.png', 'OHMYLAB VIETNAM COMPANY LIMITED\r\nWE ARE NOT OUT-SOURCING COMPANY. We develop and operate our products used by the group\'s subsidiaries and other travel companies in the form of services.\r\nWE ARE NOT A STARTUP. We work under a group that has a stable business. However, we work as creative and agile as start-ups.\r\nWE ARE EXPERTS. We work under the latest system development process with Microsoft MVP, Certified Scrum Master, Certified Information Systems Auditor. \r\n\r\nYour Journey Begins HERE\r\n\r\nOHMYLAB Co., Ltd. is a IT company under Orenge Partners of Japan, a professional travel management and hotel management group. We aim to become a travel IT company with unrivaled technology in Asia. We strive to build a sustainable high-level process and system to accomplish this.', 'https://OHMYLABVIETNAM.com', '988936354', 2, '2'),
        // (7, 13, 'GARENA VN/ Sea Group', '8', '65 Lê Lợi, SaiGon Center 2 - Takashimaya District 1 Ho Chi Minh', '3', 'public/images/company/cs2B7CBxfQgarena-vn-sea-group-logo-170-151.png', '+One of fastest-growing technology companies in Vietnam.\r\n+Found 2009 and reached 1,300+ employees in Aug, 2015.\r\n+50 Point of Customer Service nationwide besides 3 offices in Hanoi, Ho Chi Minh and Danang cities', 'https://www.garena.vn', '0168855861', 2, '1');
        // UPDATE `company` SET `created_at`='2018-04-09 00:00:00',`updated_at`='2018-04-09 00:00:00'

    }
}
